///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace sample
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
	/// <summary>
	/// The class representing the sampleRepository element repository.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
	[RepositoryFolder("b6c2519e-f0f2-4c29-b588-8f177271d79c")]
	public partial class sampleRepository : RepoGenBaseFolder
	{
		static sampleRepository instance = new sampleRepository();

		/// <summary>
		/// Gets the singleton class instance representing the sampleRepository element repository.
		/// </summary>
		[RepositoryFolder("b6c2519e-f0f2-4c29-b588-8f177271d79c")]
		public static sampleRepository Instance
		{
			get { return instance; }
		}

		/// <summary>
		/// Repository class constructor.
		/// </summary>
		public sampleRepository() 
			: base("sampleRepository", "/", null, 0, false, "b6c2519e-f0f2-4c29-b588-8f177271d79c", ".\\RepositoryImages\\sampleRepositoryb6c2519e.rximgres")
		{
		}

#region Variables

#endregion

		/// <summary>
		/// The Self item info.
		/// </summary>
		[RepositoryItemInfo("b6c2519e-f0f2-4c29-b588-8f177271d79c")]
		public virtual RepoItemInfo SelfInfo
		{
			get
			{
				return _selfInfo;
			}
		}
	}

	/// <summary>
	/// Inner folder classes.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
	public partial class sampleRepositoryFolders
	{
	}
#pragma warning restore 0436
}
